services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./services/nginx
    ports:
      - '80:80'
  web:
    mem_limit: 256m
    hostname: web
    ports:
      - '3002:3002'
      - '24678:24678'
    expose:
      - 3002
      - 24678
    build:
      dockerfile: Dockerfile.dev
      context: ./services/web